### ISSUE TITLE
Unlisted flag

### ISSUE THREAD

**Issue by thakyZ** [tupton/pastebin-cl#3]
I know there is already a flag for the script to post a paste as hidden, but could you by chance add a flag to post as unlisted?

**Comment by tupton** [comment]
According to the [API docs](https://pastebin.com/api#4), there are three values for the `api_paste_private` parameter:

> api_paste_private - this makes a paste public, unlisted or private, public = 0, unlisted = 1, private = 2

If you give the `--paste-private` option to this script, it will send `api_paste_private=1`, which _should_ be unlisted. Of course, that means that the private option ("2") isn't possible to send with this script.

**Comment by thakyZ** [comment]
Ah ok Thank you very much
